### ISSUE TITLE
Error: Cannot find module 'GVN'

### ISSUE THREAD

**Issue by drom** [indutny/wasm-cli#1]
``` sh
<>/wasm-experiments> echo 'void main() {} export main' > empty.wasm
<>/wasm-experiments> ./node_modules/.bin/wasm empty.wasm 
module.js:338
    throw err;
    ^

Error: Cannot find module 'GVN'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<>/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/base/gvn/same-node.js:4:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by indutny** [comment]
Thanks, should be fixed now. Please update!
