### ISSUE TITLE
TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by drom** [indutny/wasm-cli#2]
``` sh
drom@drom:~/work/github/drom/wasm-experiments> ./node_modules/.bin/wasm ./node_modules/wasm-cli/example/hello-world.wasm                                                              
/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:488                                            
    index = entry.index;                                                                                                                                                              
                 ^                                                                                                                                                                    
TypeError: Cannot read property 'index' of undefined                                                                                                                                  
    at CFGBuilder.buildCall (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:488:18)           
    at CFGBuilder.buildExpression (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:257:17)     
    at CFGBuilder.buildStatement (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:213:15)      
    at CFGBuilder.buildBlock (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:180:10)          
    at CFGBuilder.buildFunction (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:99:8)         
    at CFGBuilder.build (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:72:19)                
    at Object.build (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/wasm-cfg/lib/wasm-cfg/builder.js:35:37)                    
    at Compiler.generateCode (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/compiler.js:27:23)                                    
    at Compiler.compile (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/compiler.js:55:19)                                         
    at Object.<anonymous> (/home/drom/work/github/drom/wasm-experiments/node_modules/wasm-cli/bin/wasm:14:21)                                                                         
drom@drom:~/work/github/drom/wasm-experiments>                                                                                                                                        
```

**Comment by indutny** [comment]
Good catch! Please try updating!
