### ISSUE TITLE
Failed at the wasm-jit@1.1.1 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by tiye** [indutny/wasm-cli#3]
Ubuntu:

``` text
➤➤ sudo cnpm i -g wasm-cli

> mmap.js@1.0.1 install /usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/mmap.js
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/mmap.js/build'
  CXX(target) Release/obj.target/mmap/src/mmap.o
  SOLINK_MODULE(target) Release/obj.target/mmap.node
  SOLINK_MODULE(target) Release/obj.target/mmap.node: Finished
  COPY Release/mmap.node
make: Leaving directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/mmap.js/build'

> ref@1.2.0 install /usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/node_modules/ref
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/node_modules/ref/build'

> jit.js@1.17.0 install /usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/build'
  CXX(target) Release/obj.target/jit/src/jit.o
  SOLINK_MODULE(target) Release/obj.target/jit.node
  SOLINK_MODULE(target) Release/obj.target/jit.node: Finished
  COPY Release/jit.node
make: Leaving directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/build'

> wasm-jit@1.1.1 install /usr/lib/node_modules/wasm-cli/node_modules/wasm-jit
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/build'
  CXX(target) Release/obj.target/std/src/std.o
../src/std.cc:25:3: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
   space.ptr = nullptr;
   ^
../src/std.cc: In destructor ‘wasm::std::WasmContext::~WasmContext()’:
../src/std.cc:25:15: error: ‘nullptr’ was not declared in this scope
   space.ptr = nullptr;
               ^
../src/std.cc: In member function ‘uint8_t* wasm::std::WasmContext::Load(uintptr_t, uintptr_t)’:
../src/std.cc:43:12: error: ‘nullptr’ was not declared in this scope
     return nullptr;
            ^
../src/std.cc: In static member function ‘static void wasm::std::WasmContext::Print(void*, uintptr_t, uintptr_t)’:
../src/std.cc:80:15: error: ‘nullptr’ was not declared in this scope
   if (data == nullptr)
               ^
../src/std.cc: In function ‘v8::Local<v8::Value> wasm::std::GetFnPtr(uintptr_t)’:
../src/std.cc:92:25: error: ‘nullptr’ was not declared in this scope
                         nullptr).ToLocalChecked();
                         ^
../src/std.cc:93:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/std/src/std.o] Error 1
make: Leaving directory `/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "node" "/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/wasm-cli/node_modules/wasm-jit
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "node" "/usr/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/home/chen/.cnpmrc" "--disturl=https://npm.taobao.org/dist" "--cache=/home/chen/.npm/.cache_cnpm" "--registry=https://registry.npm.taobao.org" "i" "-g" "wasm-cli"
npm ERR! node v0.10.40
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! wasm-jit@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wasm-jit@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the wasm-jit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls wasm-jit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chen/npm-debug.log
```

OS X:

``` text
➤➤ npm i -g wasm-cli

> mmap.js@1.0.1 install /usr/local/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/mmap.js
> node-gyp rebuild

  CXX(target) Release/obj.target/mmap/src/mmap.o
  SOLINK_MODULE(target) Release/mmap.node
/
> ref@1.2.0 install /usr/local/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node

> jit.js@1.17.0 install /usr/local/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/jit.js
> node-gyp rebuild

  CXX(target) Release/obj.target/jit/src/jit.o
  SOLINK_MODULE(target) Release/jit.node

> wasm-jit@1.1.1 install /usr/local/lib/node_modules/wasm-cli/node_modules/wasm-jit
> node-gyp rebuild

  CXX(target) Release/obj.target/std/src/std.o
../src/std.cc:25:15: error: use of undeclared identifier 'nullptr'
  space.ptr = nullptr;
              ^
../src/std.cc:43:12: error: use of undeclared identifier 'nullptr'
    return nullptr;
           ^
../src/std.cc:67:22: warning: offset of on non-POD type 'wasm::std::WasmContext' [-Winvalid-offsetof]
  WasmContext* ctx = container_of(ictx, WasmContext, space);
                     ^                               ~~~~~
../src/std.cc:10:33: note: expanded from macro 'container_of'
    ((type *) ((char *) (ptr) - offsetof(type, member)))
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/stddef.h:87:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^
../src/std.cc:78:22: warning: offset of on non-POD type 'wasm::std::WasmContext' [-Winvalid-offsetof]
  WasmContext* ctx = container_of(ictx, WasmContext, space);
                     ^                               ~~~~~
../src/std.cc:10:33: note: expanded from macro 'container_of'
    ((type *) ((char *) (ptr) - offsetof(type, member)))
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/stddef.h:87:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^
../src/std.cc:80:15: error: use of undeclared identifier 'nullptr'
  if (data == nullptr)
              ^
../src/std.cc:92:25: error: use of undeclared identifier 'nullptr'
                        nullptr).ToLocalChecked();
                        ^
2 warnings and 4 errors generated.
make: *** [Release/obj.target/std/src/std.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/wasm-cli/node_modules/wasm-jit
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-g" "wasm-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! wasm-jit@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wasm-jit@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the wasm-jit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls wasm-jit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/etc/nginx/sites-enabled/npm-debug.log
```

**Comment by indutny** [comment]
Should be fixed now, sorry!

**Comment by tiye** [comment]
Both installed now. My first time running WASM code, finally >_<

It's fine on OS X now running the demo. While i throws error on Linux, does this log help:

``` text
➤➤ wasm a.wasm

/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/base/reductions/combo-analysis/index.js:20
  this.map = new Map();
                 ^
ReferenceError: Map is not defined
    at ComboAnalysis.start (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/base/reductions/combo-analysis/index.js:20:18)
    at Reducer.reduce (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/node_modules/json-pipeline-reducer/lib/reducer.js:29:24)
    at Pipeline.reduce (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/pipeline.js:54:11)
    at Pipeline.compile (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/pipeline.js:30:8)
    at Compiler.generateCode (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/compiler.js:45:14)
    at Compiler.compile (/usr/lib/node_modules/wasm-cli/node_modules/wasm-jit/lib/wasm/compiler.js:55:19)
    at Object.<anonymous> (/usr/lib/node_modules/wasm-cli/bin/wasm:14:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
➤➤ cat a.wasm

void main() {}
export main
```

**Comment by indutny** [comment]
@jiyinyiyong I guess you are using old node.js version, that does not support modern ECMA script versions. Try updating to 4.x ;)

**Comment by tiye** [comment]
It's an old Ubuntu VPS with node 0.10.x I'll try to update Node. Thanks for replying.

---

update: now working on Linux~
